KingsCafe/Models/tblFoodProduct.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoodProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFoodProduct()
        {
            this.tblIngredientLinkings = new HashSet<tblIngredientLinking>();
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int FOOD_PRODUCTS_ID { get; set; }
        public string FOOD_PRODUCTS_NAME { get; set; }
        public decimal FOOD_PRODUCTS_PRICE { get; set; }
        public string FOOD_PRODUCTS_PICTURE { get; set; }
        [notmapped]
        public decimal Quantity { get; set; }
        public int FOOD_CATEGORY_FID { get; set; }
        public string PicLink { get; set; }
    
        public virtual tblFoodCategory tblFoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblIngredientLinking> tblIngredientLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
    }

    internal class notmappedAttribute : Attribute
    {
    }
}

KingsCafe/Controllers/tblFoodProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingsCafe.Models;
using KingsCafe.Utills;

namespace KingsCafe.Controllers
{
    public class tblFoodProductsController : Controller
    {
        private dbKingsCafeEntities db = new dbKingsCafeEntities();

        // GET: tblFoodProducts
        public ActionResult Index()
        {
            var tblFoodProducts = db.tblFoodProducts.Include(t => t.tblFoodCategory);
            return View(tblFoodProducts.ToList());
        }

        // GET: tblFoodProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFoodProduct tblFoodProduct = db.tblFoodProducts.Find(id);
            if (tblFoodProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblFoodProduct);
        }

        // GET: tblFoodProducts/Create
        public ActionResult Create()
        {
            ViewBag.FOOD_CATEGORY_FID = new SelectList(db.tblFoodCategories, "FOOD_CATEGORY_ID", "FOOD_CATEGORY_NAME");
            return View();
        }

        // POST: tblFoodProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(tblFoodProduct tblFoodProduct,HttpPostedFileBase pic)
        {
            string fullpath = Server.MapPath("~/content/webpics/" + pic.FileName);
            pic.SaveAs(fullpath);
            tblFoodProduct.FOOD_PRODUCTS_PICTURE = "~/content/webpics/" + pic.FileName;
           var res= UploadCloud.firebaseUpload(pic);
            tblFoodProduct.PicLink =  await res;
            if (ModelState.IsValid)
            {
                
                db.tblFoodProducts.Add(tblFoodProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FOOD_CATEGORY_FID = new SelectList(db.tblFoodCategories, "FOOD_CATEGORY_ID", "FOOD_CATEGORY_NAME", tblFoodProduct.FOOD_CATEGORY_FID);
            return View(tblFoodProduct);
        }

        // GET: tblFoodProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFoodProduct tblFoodProduct = db.tblFoodProducts.Find(id);
            if (tblFoodProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.FOOD_CATEGORY_FID = new SelectList(db.tblFoodCategories, "FOOD_CATEGORY_ID", "FOOD_CATEGORY_NAME", tblFoodProduct.FOOD_CATEGORY_FID);
            return View(tblFoodProduct);
        }

        // POST: tblFoodProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(tblFoodProduct tblFoodProduct, HttpPostedFileBase pic)
        {
            if (pic != null)
            { 
            string fullpath = Server.MapPath("~/content/webpics" + pic.FileName);
            pic.SaveAs(fullpath);
            tblFoodProduct.FOOD_PRODUCTS_PICTURE = "~/content/webpics" + pic.FileName;
                var res = UploadCloud.firebaseUpload(pic);
                tblFoodProduct.PicLink = await res;
            }

            if (ModelState.IsValid)
            {
                db.Entry(tblFoodProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FOOD_CATEGORY_FID = new SelectList(db.tblFoodCategories, "FOOD_CATEGORY_ID", "FOOD_CATEGORY_NAME", tblFoodProduct.FOOD_CATEGORY_FID);
            return View(tblFoodProduct);
        }

        // GET: tblFoodProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFoodProduct tblFoodProduct = db.tblFoodProducts.Find(id);
            if (tblFoodProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblFoodProduct);
        }

        // POST: tblFoodProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblFoodProduct tblFoodProduct = db.tblFoodProducts.Find(id);
            db.tblFoodProducts.Remove(tblFoodProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingsCafe/Views/tblFoodProducts/Create.cshtml
@model KingsCafe.Models.tblFoodProduct

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Create</h2>

@using (Html.BeginForm("create","tblfoodproducts",FormMethod.Post,new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblFoodProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_PRODUCTS_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_PRODUCTS_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_PRODUCTS_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_PRODUCTS_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_PICTURE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="pic" type="file" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_CATEGORY_FID, "FOOD_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FOOD_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FOOD_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","tblFoodProducts") " class="btn btn-primary glyphicon glyphicon-backward"> </a>

</div>

KingsCafe/Views/tblFoodProducts/Delete.cshtml
@model KingsCafe.Models.tblFoodProduct

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-center">Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblFoodProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_PRODUCTS_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_PRODUCTS_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_PICTURE)
        </dt>

        <dd>
            <img src="@Url.Content(Model.FOOD_PRODUCTS_PICTURE)" height="100" width="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFoodCategory.FOOD_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFoodCategory.FOOD_CATEGORY_NAME)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a href="@Url.Action("Index","tblFoodProducts") " class="btn btn-primary glyphicon glyphicon-backward"> </a>


</div>
    }
</div>

KingsCafe/Views/tblFoodProducts/Details.cshtml
@model KingsCafe.Models.tblFoodProduct

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">Details</h2>

<div>
    <h4>tblFoodProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_PRODUCTS_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_PRODUCTS_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_PRODUCTS_PICTURE)
        </dt>

        <dd>
            <img src="@Url.Content(Model.FOOD_PRODUCTS_PICTURE)" height="100" width="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFoodCategory.FOOD_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFoodCategory.FOOD_CATEGORY_NAME)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit","tblFoodProducts" , new { id=Model.FOOD_PRODUCTS_ID })" class="btn btn-primary glyphicon glyphicon-edit"> </a>
    <a href="@Url.Action("Index","tblFoodProducts" , new { id=Model.FOOD_PRODUCTS_ID })" class="btn btn-primary glyphicon glyphicon-backward"> </a>


    
</p>

KingsCafe/Views/tblFoodProducts/Edit.cshtml
@model KingsCafe.Models.tblFoodProduct

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Edit</h2>

@using (Html.BeginForm("edit", "tblfoodproducts", FormMethod.Post, new {enctype= "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblFoodProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FOOD_PRODUCTS_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_PRODUCTS_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_PRODUCTS_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_PRODUCTS_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_PRODUCTS_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_PRODUCTS_PICTURE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pic" />
                <img src="@Url.Content(Model.FOOD_PRODUCTS_PICTURE)" height="100" width="100" />
                
                @Html.HiddenFor(model => model.FOOD_PRODUCTS_PICTURE)
                @Html.EditorFor(model => model.FOOD_PRODUCTS_PICTURE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_PRODUCTS_PICTURE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_CATEGORY_FID, "FOOD_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FOOD_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FOOD_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","tblFoodProducts" , new { id=Model.FOOD_PRODUCTS_ID })" class="btn btn-primary glyphicon glyphicon-backward"> </a>

</div>

KingsCafe/Views/tblFoodProducts/Index.cshtml
@model IEnumerable<KingsCafe.Models.tblFoodProduct>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Manage Product</h2>

<p>
    <a href="@Url.Action("create","tblFoodProducts")" class="btn btn-primary"> Create product </a>

</p>
<table class="table">
    <tr>
        <th>
          Category Name 
        </th>
        <th>
          Product Name
           
        </th>
        <th>
         Product Price
        </th>
        <th>
            Product Picture
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.tblFoodCategory.FOOD_CATEGORY_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FOOD_PRODUCTS_NAME)
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FOOD_PRODUCTS_PRICE)
            
        </td>
        <td>
            <img src="@Url.Content(item.FOOD_PRODUCTS_PICTURE)" height="100" width="100"/>
        </td>
        <td>
            <a href="@Url.Action("edit","tblFoodProducts",new { id=item.FOOD_PRODUCTS_ID })" class="btn btn-primary glyphicon glyphicon-edit"></a> |
            <a href="@Url.Action("details","tblFoodProducts",new { id=item.FOOD_PRODUCTS_ID })" class="btn btn-success glyphicon glyphicon-book"></a> |
            <a href="@Url.Action("delete","tblFoodProducts",new { id=item.FOOD_PRODUCTS_ID })" class="btn btn-danger glyphicon glyphicon-remove"></a>



            @*@Html.ActionLink("Edit", "Edit", new { id=item.FOOD_PRODUCTS_ID }) |
        @Html.ActionLink("Details", "Details", new { id=item.FOOD_PRODUCTS_ID }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.FOOD_PRODUCTS_ID })*@
        </td>
    </tr>
}

</table>