KingsCafe/Controllers/AdminsideController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KingsCafe.Models;

namespace KingsCafe.Controllers
{
    public class AdminsideController : Controller
    {

        dbKingsCafeEntities db = new dbKingsCafeEntities();
        // GET: Adminside
        public ActionResult NewOrders()
        {

           var orderlist=  db.tblOrders.Where(x => x.ORDER_STATUS == "Booked").ToList();
            return View(orderlist);
        }
        public ActionResult ProceedOrders()
        {

           var orderlist=  db.tblOrders.Where(x => x.ORDER_STATUS == "Proceed").ToList();
            return View(orderlist);
        }
        public ActionResult DeliveredOrders()
        {

           var orderlist=  db.tblOrders.Where(x => x.ORDER_STATUS == "Delivered").ToList();
            return View(orderlist);
        }
        public ActionResult Invoice(int id)
        {
           var invoicedata=  db.tblOrders.Where(x => x.ORDER_ID == id).FirstOrDefault();
            return View(invoicedata);
        }
        public ActionResult Sendtoproceed(int id)
        {
           var Orderdata=  db.tblOrders.Find(id);
            Orderdata.ORDER_STATUS = "Proceed";
            db.Entry(Orderdata).State = EntityState.Modified;
            db.SaveChanges();
            TempData["msg"] = "  Your order is " + id + " now in proceed list ";
            return RedirectToAction("NewOrders");
        }
        public ActionResult SendToDelivered(int id)
        {
           var Orderdata=  db.tblOrders.Find(id);
            Orderdata.ORDER_STATUS = "Delivered";
            db.Entry(Orderdata).State = EntityState.Modified;
            db.SaveChanges();
            TempData["msg"] = " Your order is " + id + " now in delivered list ";
            return RedirectToAction("ProceedOrders");
        }
    }
}

KingsCafe/Views/Adminside/DeliveredOrders.cshtml
@model IEnumerable<KingsCafe.Models.tblOrder>

@{
    ViewBag.Title = "DeliveredOrders";
}

<h3 class="center"> Delivered Orders</h3>

<table class="table table-bordered">
    <tr>
        <th>
          Order ID
        </th>
        <th>
          Order Customer Name
        </th>
        <th>
           Order Customer Address
        </th>
        <th>
            Order Customer Contact
        </th>
       
        <th>
            Order Status
        </th>
        <th>
           Order Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_ADDRESS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_CONTACT)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_STATUS)
        </td>
        <td>
           @item.ORDER_DATE.ToLongDateString()
        </td>
        <td>
            <a href="@Url.Action("Invoice","Adminside", new { id= item.ORDER_ID })" class="btn btn-primary">Invoice</a>
         </td>
    </tr>
}
    
</table>

KingsCafe/Views/Adminside/Invoice.cshtml
@model KingsCafe.Models.tblOrder

@{
    ViewBag.Title = "Invoice";
    decimal total = 0;
}

<h3 class="center">Invoice</h3>
<table class=" table table-bordered">
    <tr>
        <td> <b>Name</b>   </td>
        <td> @Model.ORDER_CUSTOMER_NAME </td>
        <td> <b>Address</b>  </td>
        <td> @Model.ORDER_CUSTOMER_ADDRESS </td>
        <td>  <b>Contact</b>  </td>
        <td> @Model.ORDER_CUSTOMER_CONTACT </td>
    </tr>
    <tr>
        <td> <b>Status</b>  </td>
        <td> @Model.ORDER_STATUS </td>
        <td> <b>Date</b> </td>
        <td> @Model.ORDER_DATE.ToLongDateString() </td>
        
    </tr>
</table>

<table class=" table table-bordered">
    <tr>
        <td><b>Product Name</b> </td> 
        <td> <b>Price</b> </td>
        <td> <b>Quantity</b></td> 
        <td><b>Sub Total</b></td>
        
    </tr>
    @foreach (var item in Model.tblOrderDetails)
    {
        total += (item.ORDER_DETAILS_PRICE * item.ORDER_DETAILS_QUANTITY);
        <tr>
            <td>@item.tblFoodProduct.FOOD_PRODUCTS_NAME </td>
            <td>@item.ORDER_DETAILS_PRICE</td>
            <td>@item.ORDER_DETAILS_QUANTITY</td>
            <td>@(item.ORDER_DETAILS_PRICE*item.ORDER_DETAILS_QUANTITY)</td>
            
        </tr>
}
    <tr>
        <td colspan="3"><b>Total</b></td>
        <td><b>@total</b></td>
    </tr>
    
    <tr>
        
        <td>
            <a href="@Url.Action("NewOrders","Adminside")" class="btn btn-primary" >Back to list</a>
        </td>
    </tr>
</table>

KingsCafe/Views/Adminside/NewOrders.cshtml
@model IEnumerable<KingsCafe.Models.tblOrder>

@{
    ViewBag.Title = "NewOrders";
}

<h3 class="center"> New Orders</h3>

<table class="table table-bordered">
    <tr>
        <th>
          Order ID
        </th>
        <th>
          Order Customer Name
        </th>
        <th>
           Order Customer Address
        </th>
        <th>
            Order Customer Contact
        </th>
       
        <th>
            Order Status
        </th>
        <th>
           Order Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_ADDRESS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_CONTACT)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_STATUS)
        </td>
        <td>
           @item.ORDER_DATE.ToLongDateString()
        </td>
        <td>
            <a href="@Url.Action("Invoice","Adminside", new { id= item.ORDER_ID })" class="btn btn-primary">Invoice</a>
            <a href="@Url.Action("Sendtoproceed","Adminside", new { id= item.ORDER_ID })" class="btn btn-primary">Update To Proceed</a>
        </td>
    </tr>
}
    
</table>

KingsCafe/Views/Adminside/ProceedOrders.cshtml
@model IEnumerable<KingsCafe.Models.tblOrder>

@{
    ViewBag.Title = "NewOrders";
}

<h3 class="center"> New Orders</h3>

<table class="table table-bordered">
    <tr>
        <th>
          Order ID
        </th>
        <th>
          Order Customer Name
        </th>
        <th>
           Order Customer Address
        </th>
        <th>
            Order Customer Contact
        </th>
       
        <th>
            Order Status
        </th>
        <th>
           Order Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_ADDRESS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_CUSTOMER_CONTACT)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.ORDER_STATUS)
        </td>
        <td>
           @item.ORDER_DATE.ToLongDateString()
        </td>
        <td>
            <a href="@Url.Action("Invoice","Adminside", new { id= item.ORDER_ID })" class="btn btn-primary">Invoice</a>
            <a href="@Url.Action("SendToDelivered","Adminside", new { id= item.ORDER_ID })" class="btn btn-primary">Update To Delivered</a>
        </td>
    </tr>
}
    
</table>