KingsCafe/Models/tblIngredient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsCafe.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIngredient()
        {
            this.tblIngredientLinkings = new HashSet<tblIngredientLinking>();
            this.tblOrderLinkings = new HashSet<tblOrderLinking>();
            this.tblOrderPurchaseDetails = new HashSet<tblOrderPurchaseDetail>();
        }
    
        public int INGREDIENT_ID { get; set; }
        public string INGREDIENT_NAME { get; set; }
        public decimal INGREDIENT_PRICE { get; set; }
        [notmapped]
        public decimal Quantity { get; set; }
        public decimal INGREDIENT_UNIT_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblIngredientLinking> tblIngredientLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblOrderLinking> tblOrderLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblOrderPurchaseDetail> tblOrderPurchaseDetails { get; set; }
    }
}

KingsCafe/Controllers/tblIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingsCafe.Models;

namespace KingsCafe.Controllers
{
    public class tblIngredientsController : Controller
    {
        private dbKingsCafeEntities db = new dbKingsCafeEntities();

        // GET: tblIngredients
        public ActionResult Index()
        {
            return View(db.tblIngredients.ToList());
        }

        // GET: tblIngredients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblIngredient tblIngredient = db.tblIngredients.Find(id);
            if (tblIngredient == null)
            {
                return HttpNotFound();
            }
            return View(tblIngredient);
        }

        // GET: tblIngredients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblIngredients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tblIngredient tblIngredient)
        {
            if (ModelState.IsValid)
            {
                db.tblIngredients.Add(tblIngredient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblIngredient);
        }

        // GET: tblIngredients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblIngredient tblIngredient = db.tblIngredients.Find(id);
            if (tblIngredient == null)
            {
                return HttpNotFound();
            }
            return View(tblIngredient);
        }

        // POST: tblIngredients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( tblIngredient tblIngredient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblIngredient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblIngredient);
        }

        // GET: tblIngredients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblIngredient tblIngredient = db.tblIngredients.Find(id);
            if (tblIngredient == null)
            {
                return HttpNotFound();
            }
            return View(tblIngredient);
        }

        // POST: tblIngredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblIngredient tblIngredient = db.tblIngredients.Find(id);
            db.tblIngredients.Remove(tblIngredient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingsCafe/Views/tblIngredients/Create.cshtml
@model KingsCafe.Models.tblIngredient

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Create</h2>

@using (Html.BeginForm("Create", "tblIngredients", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblIngredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_UNIT_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_UNIT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_UNIT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","tblIngredients") " class="btn btn-primary glyphicon glyphicon-backward"> </a>

</div>

KingsCafe/Views/tblIngredients/Delete.cshtml
@model KingsCafe.Models.tblIngredient

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-center">Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblIngredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_UNIT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_UNIT_PRICE)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("Index","tblIngredients") " class="btn btn-primary glyphicon glyphicon-backward"> </a>

        </div>

        @*<div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>*@
    }
</div>

KingsCafe/Views/tblIngredients/Details.cshtml
@model KingsCafe.Models.tblIngredient

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">Details</h2>


<div>
    <h4>tblIngredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INGREDIENT_UNIT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INGREDIENT_UNIT_PRICE)
        </dd>

    </dl>
</div>
<p>

    <a href="@Url.Action("Edit","tblIngredients" , new { id=Model.INGREDIENT_ID })" class="btn btn-primary glyphicon glyphicon-edit"> </a>
    <a href="@Url.Action("Index","tblIngredients" , new { id=Model.INGREDIENT_ID })" class="btn btn-primary glyphicon glyphicon-backward"> </a>


    @*@Html.ActionLink("Edit", "Edit", new { id = Model.INGREDIENT_ID }) |
        @Html.ActionLink("Back to List", "Index")*@
</p>

KingsCafe/Views/tblIngredients/Edit.cshtml
@model KingsCafe.Models.tblIngredient

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Edit</h2>

@using (Html.BeginForm("edit", "tblIngredients", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblIngredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.INGREDIENT_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INGREDIENT_UNIT_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INGREDIENT_UNIT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INGREDIENT_UNIT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","tblIngredients" , new { id=Model.INGREDIENT_ID })" class="btn btn-primary glyphicon glyphicon-backward"> </a>

</div>

KingsCafe/Views/tblIngredients/Index.cshtml
@model IEnumerable<KingsCafe.Models.tblIngredient>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Index</h2>

<p>
    <a href="@Url.Action("Create","tblIngredients")" class="btn btn-primary"> Create Food Ingredients </a>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.INGREDIENT_NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.INGREDIENT_PRICE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.INGREDIENT_UNIT_PRICE)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.INGREDIENT_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.INGREDIENT_PRICE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.INGREDIENT_UNIT_PRICE)
        </td>
        <td>
            <a href="@Url.Action("edit","tblIngredients",new { id=item.INGREDIENT_ID })" class="btn btn-primary glyphicon glyphicon-edit"></a> |
            <a href="@Url.Action("details","tblIngredients",new { id=item.INGREDIENT_ID })" class="btn btn-success glyphicon glyphicon-book"></a> |
            <a href="@Url.Action("delete","tblIngredients",new { id=item.INGREDIENT_ID })" class="btn btn-danger glyphicon glyphicon-remove"></a>
        </td>
    </tr>
}

</table>